version: "3"

services:
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:latest@sha256:c176112df6a6aac970d54b0b2e2db950642378496c6967adc8a401179819fab0
    command:
      - run
      - /template.js
    volumes:
      - ./template.js:/template.js:ro
    depends_on:
      - otel-collector
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector:latest@sha256:b54b114431b2aa031c28f590507b4a17daabd59a4d797eb7fddd7988b4d3e3ea
    command:
      - --config=/collector-config.yaml
    volumes:
      - ../shared/collector-config.yaml:/collector-config.yaml:ro
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "55678-55679:55678-55679"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
